Attempted task 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,9 +1,26 @@
 #!/usr/bin/env bash
-# Check if all required parameters are provided
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if all required parameters are provided
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+PATH_TO_FILE="$1"
+IP="$2"
+USERNAME="$3"
+SSH_KEY="$4"
+
+# Disable strict host key checking for scp
+SCP_OPTIONS="-o StrictHostKeyChecking=no"
+
+# Transfer the file using scp
+scp $SCP_OPTIONS -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+# Check the exit status of scp
+if [ "$?" -eq 0 ]; then
+    echo "File transfer completed successfully."
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    echo "File transfer failed."
 fi
